Install tools (#13)
Tools can be defined in a go.mod and invoked via `go tool <name>`. We
can grab the package and version for a tool from go.mod and install it.

The short name for a tool may be used, but will fail if ambiguous. Using
the fully qualified tool name is more stable.

Using the tool input is mutually exclusive with the package input. The
version input is only valid with a package.

Signed-off-by: Scott Andrews <scott@andrews.me>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -5,10 +5,11 @@ branding:
 description: "Install a go package"
 inputs:
   package:
-    description: go package to install
-    required: true
+    description: go package to install. Exactly one of 'package' or 'tool' is required
   version:
-    description: version of go package to install
+    description: version of go package to install. Only valid with 'package'
+  tool:
+    description: tool defined in go.mod to install. Exactly one of 'package' or 'tool' is required
   working-directory:
     description: directory containing a go.mod file defining the package's version
     default: '.'
@@ -40,6 +41,20 @@ runs:
 
       package="${{ inputs.package }}"
       version="${{ inputs.version }}"
+      tool="${{ inputs.tool }}"
+
+      if [[ "${package}" == "" && "${tool}" == "" ]] ; then
+        echo "::error title=Missing required input::either 'package' or 'tool' input must be defined"
+        exit 1
+      fi
+      if [[ "${package}" != "" && "${tool}" != "" ]] ; then
+        echo "::error title=Mutually exclusive input::either 'package' or 'tool' input must be defined, not both"
+        exit 1
+      fi
+      if [[ "${version}" != "" && "${package}" == "" ]] ; then
+        echo "::error title=Invalid input::'version' input is only valid in conjunction with 'package'"
+        exit 1
+      fi
 
       goversion="$(go env GOVERSION)"
       gotoolchain="$(go env GOTOOLCHAIN)"
@@ -58,6 +73,43 @@ runs:
       echo "##[group]verify package and version"
         normalized_version=""
         normalized_module="${package}"
+
+        if [[ "${tool}" != "" ]] ; then
+          # resolve the corresponding package for the tool as the cache key uses the package and version of the module for the package
+
+          tools=$(go mod edit -json | jq -r '.Tool.[].Path')
+
+          # find exact match
+          while IFS= read -r item; do
+            if [[ "${item}" == "${tool}" ]] ; then
+              if [[ "${normalized_module}" != "" ]] ; then
+                echo "::error title=Duplicate tool::tool \"${tool}\" found twice in go.mod"
+                exit 1
+              fi
+              echo "Found tool: ${item}"
+              normalized_module="${item}"
+            fi
+          done <<< "${tools}"
+
+          # find shorthand match
+          if [[ "${normalized_module}" == "" ]] ; then
+            while IFS= read -r item; do
+              if [[ "${item}" == */"${tool}" ]] ; then
+                if [[ "${normalized_module}" != "" ]] ; then
+                  echo "::error title=Ambiguous tool::tool \"${tool}\" found twice in go.mod"
+                  exit 1
+                fi
+                echo "Found tool: ${tool} -> ${item}"
+                normalized_module="${item}"
+              fi
+            done <<< "${tools}"
+          fi
+
+          if [[ "${normalized_module}" == "" ]] ; then
+            echo "::error title=Tool not defined::tool \"${tool}\" not found in go.mod"
+            exit 1
+          fi
+        fi
 
         while true; do
           if ! normalized_version="$(go list -m -f '{{.Version}}' "${normalized_module}${version:+@${version}}")" ; then
@@ -106,6 +158,7 @@ runs:
 
       package="${{ inputs.package }}"
       version="${{ inputs.version }}"
+      tool="${{ inputs.tool }}"
       normalized_version="${{ steps.prep.outputs.normalized-version }}"
       cache_dir="${{ steps.prep.outputs.cache-dir }}"
       toolchain="${{ steps.prep.outputs.toolchain }}"
@@ -113,9 +166,17 @@ runs:
       echo "##[group]go env"
         GOTOOLCHAIN="${toolchain}" go env
       echo "##[endgroup]"
-      echo "##[group]go install ${package}${version:+@${version}}"
-        GOBIN="${cache_dir}" GOTOOLCHAIN="${toolchain}" go install "${package}@${normalized_version}"
-      echo "##[endgroup]"
+
+      if [[ "${package}" != "" ]] ; then
+        echo "##[group]go install ${package}${version:+@${version}}"
+          GOBIN="${cache_dir}" GOTOOLCHAIN="${toolchain}" go install "${package}@${normalized_version}"
+        echo "##[endgroup]"
+      elif [[ "${tool}" != "" ]] ; then
+        echo "##[group]go tool ${tool}"
+          cp $(GOTOOLCHAIN="${toolchain}" go tool -n "${tool}") "${cache_dir}/"
+        echo "##[endgroup]"
+      fi
+
       echo "provenance=source" >> "${GITHUB_OUTPUT}"
     shell: bash
     working-directory: ${{ inputs.working-directory }}
