'cache-enabled: false' to always build from source (#9)
Signed-off-by: Scott Andrews <scott@andrews.me>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -12,7 +12,7 @@ on:
 jobs:
   test:
     name: Test go-install action
-    strategy:
+    strategy: &tests
       fail-fast: false
       matrix:
         include:
@@ -20,19 +20,48 @@ jobs:
           version: latest
         - os: ubuntu-24.04-arm
           version: latest
-        # git tag
-        - version: v0.20.0
-        # git commit
-        - version: d36047ae385302d20acd872e28f036a475fb9417
+        - version: "v0.20.0" # git tag
+        - version: "d36047ae385302d20acd872e28f036a475fb9417" # git commit
+          cache-enabled: 'true'
         - working-directory: hack/crane
+          cache-enabled: true
         - version: latest
           output-path-env: CRANE
+          cache-enabled: 'false'
         - package: sigs.k8s.io/kind
           version: latest
           output: kind-latest
           output-dir: /usr/local/bin
           output-path-env: KIND
+          cache-enabled: false
           test-args: --version
+    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
+    steps:
+    - uses: actions/checkout@v6
+    - uses: actions/setup-go@v6
+      with:
+        go-version-file: hack/crane/go.mod
+        cache-dependency-path: '**/go.sum'
+    - name: Install package
+      id: install
+      uses: ./
+      with: &with-install
+        package: ${{ matrix.package || 'github.com/google/go-containerregistry/cmd/crane' }}
+        version: ${{ matrix.version }}
+        working-directory: ${{ matrix.working-directory }}
+        output: ${{ matrix.output }}
+        output-dir: ${{ matrix.output-dir }}
+        output-path-env: ${{ matrix.output-path-env }}
+        cache-enabled: ${{ matrix.cache-enabled }}
+    - name: Test install
+      run: ${{ steps.install.outputs.path }} ${{ matrix.test-args || 'version' }}
+    - name: Test install env
+      if: matrix.output-path-env
+      run: ${${{ matrix.output-path-env }}} ${{ matrix.test-args || 'version' }}
+  test-from-cache:
+    name: Test go-install action (from cache)
+    needs: test
+    strategy: *tests
     runs-on: ${{ matrix.os || 'ubuntu-latest' }}
     steps:
     - uses: actions/checkout@v6
@@ -42,15 +71,26 @@ jobs:
     - name: Install package
       id: install
       uses: ./
-      with:
-        package: ${{ matrix.package || 'github.com/google/go-containerregistry/cmd/crane' }}
-        version: ${{ matrix.version }}
-        working-directory: ${{ matrix.working-directory }}
-        output: ${{ matrix.output }}
-        output-dir: ${{ matrix.output-dir }}
-        output-path-env: ${{ matrix.output-path-env }}
+      with: *with-install
     - name: Test install
       run: ${{ steps.install.outputs.path }} ${{ matrix.test-args || 'version' }}
-    - name: Test install env
-      if: matrix.output-path-env
-      run: ${${{ matrix.output-path-env }}} ${{ matrix.test-args || 'version' }}
+    # test artifact provenance on the second job, as the first job seeds the cache
+    - name: Test provenance
+      run: |
+        set -euo pipefail
+
+        cache_enabled="${{ matrix.cache-enabled }}"
+        cache_enabled="${cache_enabled:-true}"
+        provenance="${{ steps.install.outputs.provenance }}"
+
+        echo "cache-enabled = ${cache_enabled}"
+        echo "artifact-provenance = ${provenance}"
+
+        if [[ "${cache_enabled}" == "true" && "${provenance}" != "cache" ]] ; then
+          echo "::error title=Expected cache::artifact from ${provenance}, expected to be from cache"
+          exit 1
+        fi
+        if [[ "${cache_enabled}" != "true" && "${provenance}" != "source" ]] ; then
+          echo "::error title=Expected source::artifact from ${provenance}, expected to be from source"
+          exit 1
+        fi
